name: Publish to NPM

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_n_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@yotieapp'
      - run: yarn
      - run: yarn test --ci
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
