name: Publish to Github Private Registry

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_n_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@yotieapp'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn test --ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
